{
    'name': '365Infotech Custom Bundle',
    'summary': 'All-in-one custom module installation for 365Infotech',
    'version': '18.0.1.0.0',
    'author': '365Infotech',
    'website': 'https://www.365infotech.com',
    'category': 'Customization',
    'application': True,
    'installable': True,
    'depends': [
        # Thai Localization
        'l10n_th_account_tax',
        'l10n_th_account_tax_expense',
        'l10n_th_account_tax_report',
        'l10n_th_account_wht_cert_form',
        'l10n_th_amount_to_text',
        'l10n_th_base_location',
        'l10n_th_base_sequence',
        'l10n_th_base_utils',
        'l10n_th_fonts',
        'l10n_th_partner',

        # Accounting
        'account_asset_customization',
        'account_billing',
        'account_invoice_date_check',
        'account_invoice_timestamp',
        'account_payment_collection_report',
        'account_payment_hide_payment_provider_menu',
        'amount_to_billing',
        'auto_asset_from_vendor_bill',
        'bi_manual_currency_exchange_rate',
        'cheque_management',
        'date_range',
        'effective_date_change',
        'report_xlsx',
        'sh_pdc',
        'sh_pdc_ent',

        # Purchase
        'purchase_do_smart_button',
        'purchase_hide_receipt_reminder_email',
        'purchase_note_carry_info',
        'purchase_order_status_report',
        'purchase_price_history',
        'purchase_request',
        'purchase_request_analytic_required',
        'purchase_request_cost',
        'purchase_request_line_discount_taxes',
        'purchase_request_menu_report',
        'purchase_request_note_to_po',
        'purchase_request_status_report',
        'purchase_request_vendor',
        'purchase_service_acceptance',
        'po_purchase_request_smart_button',
        'nano_discount_to_pr_no_so',

        # Sales
        'sale_analysis_report',
        'sale_auto_warehouse_van_sales',
        'sale_commission_management',
        'sale_credit_limit_warning',
        'sale_customer_pricelist_percent_limit',
        'sale_foc_enhancement',
        'sale_free_item_promo',
        'sale_hide_buttons_coupon_reward_discount',
        'sale_note_carry_info',
        'sale_order_payments_button',
        'sale_sequence_option',
        'sale_so_type',
        'saleperson_pricelist_restrict',
        'salesperson_signature',
        'show_delivery_date_at_header',
        'so_do_smart_button',

        # MRP
        'lot_manufacturing_date',
        'mrp_mold_management',
        'mrp_mps_bom_autoload',
        'mrp_mps_bom_selection_fix',
        'mrp_parallel_console',
        'mrp_scrap_finished_Good',
        'mrp_workcenter_lock',
        'transform_product_advanced',

        # Inventory & Logistics
        'inventory_expired_products_report',
        'inventory_stock_card',
        'stock_hide_check_availability_receipts',
        'stock_picking_invrefs_edit_date_done',
        'stock_transfer_info',
        'delivery_pickup_transport',
        'delivery_route_report',
        'delivery_routes_management',
        'user_location_restrictions',
        'product_custom_name',
        'product_price_guard',

        # Partner
        'contact_parent_company_view',
        'default_contact_name',
        'partner_company_type',
        'partner_customization',
        'partner_firstname',
        'partner_manual_rank',
        'partner_payment_condition',
        'partner_payment_schedule',
        'product_partner_approval_ecom_exempt',

        # OI Modules
        'oi_action_file',
        'oi_base',
        'oi_base_cache',
        'oi_jasper_report',
        'oi_pdf_viewer',
        'oi_web_selection_field_dynamic',
        'oi_web_selection_tags',
        'oi_workflow',
        'oi_workflow_purchase_order',
        'oi_workflow_purchase_request',
        'oi_workflow_sale_order',

        # Utilities & UI
        'base_location',
        'base_location_geonames_import',
        'base_sequence_option',
        'many2one_force_dropdown',
        'my_theme_translations',
        'payment_method_optional_image',
        'report_xlsx_helper',
        'web_chatter_position',

        # Line Numbering
        'psn_account_invoice_line_number',
        'psn_purchase_order_line_number',
        'psn_sale_order_line_number',
        'psn_stock_picking_line_number',

        # HR
        'hr_expense_advance_clearing',
    ],
    'data': [],
}
