{
    "name": "Sales Analysis Report",
    "summary": "Enhanced sales analysis reporting for Odoo.",
    "version": "18.0.1.0.3",
    "category": "Sales/Sales",
    "author": "365 infotech",
    "website": "https://www.365infotech.co.th/",
    "license": "LGPL-3",
    "depends": [
        "base",
        "sale",
        "account",
        "product",
        "sale_management",
        "sales_team",
        "oi_jasper_report",
        "sale_commission_management",
        "delivery_routes_management",
        "sale_so_type",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/sale_analysis_action_views.xml",
        "views/sale_menus.xml",
        "views/sale_analysis_config_views.xml",
        "wizard/sale_analysis_wizard_views.xml",
    ],
    "assets": {},
    "installable": True,
    "application": False,
    "auto_install": False,
}
